
Call for Papers
International Journal of Business and Social Science Research
ISSN: 2709-2143 

International Journal of Business and Social Science Research (IJBSSR) is open access multidisciplinary journal that publishes double-blind peer-reviewed high-quality manuscripts of interdisciplinary content and methodology. The scope of the journal is all fields of business, Economics and Social Science including, but not limited to, the following areas: Accounting Information System, Anthropology, Corporate Governance, Development Economics and Economic Policies, Education Research, Environmental Studies, Finance & Banking, History & Culture, Human Geography, Tourism and Hospitality, Insurance and Actuarial Science, COVID-19,  International Relations, Legal Studies, Marketing Research, Mass Communication, Management Information System, Management & Business Studies, Operations Research, Peace and Conflict, Philosophy, Political Science, Population Studies, Public Administration, Psychology, Quantitative and Qualitative Management, Religious Studies, Social Policy and Social Welfare, Sociology, Teaching, Tourism and Hospitality, Women Studies. education, and so on.
IJBSSR publishes original papers, review papers, conceptual framework, analytical and simulation models, case studies, empirical research, technical notes, and book reviews. Special Issues devoted to important topics in business and Social Science Research will occasionally be published. 
INDEXING:
Google Scholars, Crossref, BASE, Neliti, PKP, OpenAire, Microsoft Academic, Garuda, ASUSINDEX,
  Indonesia Onesearch, Unpaywall, Dimensions, Moraref, IDEAS etc. 

IJBSSR is inviting papers for Vol. 3 Issue No. 4, which is scheduled to be published on April 30, 2022. 
Upcoming Issue: Call for Papers Vol: 3, Issue: 5,  Publication date 31, May 2022 
However, an early submission will get preference in case of review and publication process. Send your manuscript to the editor at editor@ijbssrnet.com or contact@ijbssrnet.com
Online Submission: https://ijbssrnet.com/index.php/ijbssr/submissionguide#online  
For more information, visit the official website of the journal https://ijbssrnet.com/index.php/ijbssr 
This Journal is licensed under a Creative Commons Attribution 4.0 International License 
With Thanks
The Chief Editor
Dr. Iwan Kurniawan Subagja
International Journal of Business and Social Science Research
Contact: editor@ijbssrnet.com
Official website https://ijbssrnet.com/index.php/ijbssr 
Online Submission: https://ijbssrnet.com/index.php/ijbssr/submissionguide#online
